[2023-01-21T23:45:21.156+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:45:21.157+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:45:21.159+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:45:21.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:45:21.184+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:45:21.182+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:45:21.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:45:21.210+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.062 seconds
[2023-01-21T23:45:52.202+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:45:52.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:45:52.208+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:45:52.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:45:52.222+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:45:52.220+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:45:52.222+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:45:52.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.050 seconds
[2023-01-21T23:46:22.714+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:46:22.718+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:46:22.720+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:46:22.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:46:22.736+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:46:22.731+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:46:22.737+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:46:22.761+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.058 seconds
[2023-01-21T23:46:53.262+0000] {processor.py:153} INFO - Started process (PID=250) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:46:53.264+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:46:53.265+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:46:53.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:46:53.284+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:46:53.282+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:46:53.284+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:46:53.304+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.047 seconds
[2023-01-21T23:47:23.560+0000] {processor.py:153} INFO - Started process (PID=325) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:47:23.562+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:47:23.564+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:47:23.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:47:23.596+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:47:23.593+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:47:23.602+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:47:23.673+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.123 seconds
[2023-01-21T23:47:53.937+0000] {processor.py:153} INFO - Started process (PID=390) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:47:53.939+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:47:53.941+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:47:53.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:47:53.954+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:47:53.952+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:47:53.955+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:47:53.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.050 seconds
[2023-01-21T23:48:24.376+0000] {processor.py:153} INFO - Started process (PID=466) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:48:24.378+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:48:24.379+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:48:24.379+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:48:24.391+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:48:24.390+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:48:24.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:48:24.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.046 seconds
[2023-01-21T23:48:54.518+0000] {processor.py:153} INFO - Started process (PID=539) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:48:54.520+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:48:54.521+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:48:54.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:48:54.534+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:48:54.530+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:48:54.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:48:54.557+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.043 seconds
[2023-01-21T23:49:25.343+0000] {processor.py:153} INFO - Started process (PID=607) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:49:25.345+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:49:25.346+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:49:25.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:49:25.357+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:49:25.355+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:49:25.358+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:49:25.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.046 seconds
[2023-01-21T23:49:55.737+0000] {processor.py:153} INFO - Started process (PID=684) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:49:55.739+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:49:55.741+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:49:55.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:49:55.754+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:49:55.752+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:49:55.755+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:49:55.778+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.051 seconds
[2023-01-21T23:50:26.000+0000] {processor.py:153} INFO - Started process (PID=747) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:50:26.003+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:50:26.004+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:50:26.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:50:26.017+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:50:26.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:50:26.018+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:50:26.042+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.049 seconds
[2023-01-21T23:54:02.678+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:54:02.685+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:54:02.687+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:54:02.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:54:02.704+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:54:02.702+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:54:02.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:54:02.732+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.062 seconds
[2023-01-21T23:54:33.752+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:54:33.754+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:54:33.756+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:54:33.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:54:33.770+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:54:33.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:54:33.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:54:33.796+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.050 seconds
[2023-01-21T23:55:04.023+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:55:04.025+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:55:04.027+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:55:04.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:55:04.043+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:55:04.041+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:55:04.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:55:04.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.056 seconds
[2023-01-21T23:56:03.402+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:56:03.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:56:03.405+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:56:03.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:56:03.433+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:56:03.424+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:56:03.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:56:03.462+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.066 seconds
[2023-01-21T23:56:34.359+0000] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:56:34.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:56:34.363+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:56:34.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:56:34.375+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:56:34.373+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:56:34.376+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:56:34.406+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.064 seconds
[2023-01-21T23:57:05.158+0000] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:57:05.160+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-21T23:57:05.162+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:57:05.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:57:05.182+0000] {logging_mixin.py:137} INFO - [2023-01-21T23:57:05.180+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-21T23:57:05.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-21T23:57:05.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.060 seconds
